<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BOOPATHI-PC" ignored="4" name="Test(failed)" tests="1" failures="1" timestamp="2021-07-22T17:15:56 IST" time="0.191" errors="0">
  <testcase name="tc1" time="0.037" classname="org.rerun.Test1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.Test1.tc1(Test1.java:9)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- tc1 -->
  <testcase name="tc2" time="0.0" classname="org.rerun.Test1">
    <ignored/>
  </testcase> <!-- tc2 -->
  <testcase name="tc3" time="0.0" classname="org.rerun.Test1">
    <ignored/>
  </testcase> <!-- tc3 -->
  <testcase name="tc4" time="0.0" classname="org.rerun.Test1">
    <ignored/>
  </testcase> <!-- tc4 -->
  <testcase name="tc5" time="0.0" classname="org.rerun.Test1">
    <ignored/>
  </testcase> <!-- tc5 -->
</testsuite> <!-- Test(failed) -->
